-- Migration 017: Create study_guides table
-- Enables generation and storage of personalized study guides for focus areas

CREATE TABLE IF NOT EXISTS study_guides (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    child_id UUID REFERENCES children(id) ON DELETE CASCADE,
    concept_name TEXT NOT NULL,
    focus_area TEXT,  -- The specific area of focus (e.g., "Arithmetic errors in multiplication")
    grade_level VARCHAR(50),
    subject VARCHAR(100),
    content TEXT NOT NULL,  -- The generated study guide content
    key_points TEXT[],  -- Array of key points
    practice_recommendations TEXT[],  -- Array of practice recommendations
    common_errors TEXT[],  -- Common errors to avoid
    related_concepts TEXT[],  -- Related concepts to review
    generated_from_test_id UUID REFERENCES tests(id) ON DELETE SET NULL,
    generated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    metadata JSONB
);

CREATE INDEX IF NOT EXISTS idx_study_guides_child_id ON study_guides(child_id);
CREATE INDEX IF NOT EXISTS idx_study_guides_concept ON study_guides(concept_name);
CREATE INDEX IF NOT EXISTS idx_study_guides_test_id ON study_guides(generated_from_test_id);
CREATE INDEX IF NOT EXISTS idx_study_guides_generated_at ON study_guides(generated_at DESC);

-- Add comments for documentation
COMMENT ON TABLE study_guides IS 'Personalized study guides generated for student focus areas';
COMMENT ON COLUMN study_guides.concept_name IS 'Name of the concept this study guide covers';
COMMENT ON COLUMN study_guides.focus_area IS 'Specific area of focus (e.g., "Performance: 45%")';
COMMENT ON COLUMN study_guides.content IS 'Full study guide content generated by LLM';
COMMENT ON COLUMN study_guides.key_points IS 'Array of key learning points extracted from the guide';
COMMENT ON COLUMN study_guides.practice_recommendations IS 'Array of practice recommendations';
COMMENT ON COLUMN study_guides.common_errors IS 'Common errors identified for this focus area';
COMMENT ON COLUMN study_guides.generated_from_test_id IS 'Test that triggered this study guide generation';
